env:
  global:
    TERM=dumb

language: java
#jdk: oraclejdk7
jdk: openjdk7

install: true
before_install:
- sudo apt update -y >/dev/null 2>&1 || true
- sudo apt install --no-install-recommends -y wget curl python-pip docker-ce >/dev/null 2>&1
- sudo pip install httpie >/dev/null 2>&1
- sudo update-ca-certificates -f
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 5432 5672 27017 8080 80

script:

# spring-boot
- bash gradlew clean
- bash gradlew >/dev/null 2>&1
- ls -lah ./
- ls -lah ./build/
- ls -lah ./build/libs/
- java -jar build/libs/*.war &
- wait_for 8080
- http :8080/actuator/health
- http -a admin:admin :8080 name=max
- http -a admin:admin :8080 name=bax
- http -a admin:admin :8080
- http :8080/actuator/props
- stop_any 8080 80

# jboss (docker)
- bash gradlew >/dev/null 2>&1
- docker-compose build --force-rm --no-cache --pull
- docker-compose up --build --force-recreate --remove-orphans &
- sleep 35
- http :8080/spring-boot-jboss/actuator/health
- http -a admin:admin :8080/spring-boot-jboss name=max
- http -a admin:admin :8080/spring-boot-jboss name=bax
- http -a admin:admin :8080/spring-boot-jboss/
- http :8080/spring-boot-jboss/actuator/props
- docker-compose down -v
